/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_v1_library_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Media */
        get: operations["media_api_v1_library_media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/tweets/{tweet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tweet Detail */
        get: operations["tweet_detail_api_v1_library_tweets__tweet_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Failures */
        get: operations["failures_api_v1_library_failures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Duplicates */
        get: operations["duplicates_api_v1_library_duplicates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/archive-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Archive Runs */
        get: operations["archive_runs_api_v1_archive_runs_get"];
        put?: never;
        /** Submit Run */
        post: operations["submit_run_api_v1_archive_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/archive-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Archive Run Detail */
        get: operations["archive_run_detail_api_v1_archive_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/archive-runs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Archive Run */
        post: operations["retry_archive_run_api_v1_archive_runs__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Archive Sources */
        get: operations["archive_sources_api_v1_sources_get"];
        put?: never;
        /** Create Archive Source */
        post: operations["create_archive_source_api_v1_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Archive Source Detail */
        get: operations["archive_source_detail_api_v1_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Archive Source Records */
        post: operations["submit_archive_source_records_api_v1_sources__source_id__records_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}/submit-discovered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Archive Source Discovered */
        post: operations["submit_archive_source_discovered_api_v1_sources__source_id__submit_discovered_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Archive Source Status */
        post: operations["update_archive_source_status_api_v1_sources__source_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan Archive Source */
        post: operations["scan_archive_source_api_v1_sources__source_id__scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}/history-scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Archive Source History Scan */
        post: operations["start_archive_source_history_scan_api_v1_sources__source_id__history_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}/history-scan/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Archive Source History Scan */
        post: operations["stop_archive_source_history_scan_api_v1_sources__source_id__history_scan_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Action */
        post: operations["verify_action_api_v1_actions_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions/requeue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Requeue Action */
        post: operations["requeue_action_api_v1_actions_requeue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions/recover-interrupted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recover Interrupted Action */
        post: operations["recover_interrupted_action_api_v1_actions_recover_interrupted_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Action */
        post: operations["export_action_api_v1_actions_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/maintenance/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Maintenance Backfill */
        post: operations["maintenance_backfill_api_v1_maintenance_backfill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/maintenance/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Maintenance Verify */
        post: operations["maintenance_verify_api_v1_maintenance_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/download-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Policy */
        get: operations["download_policy_api_v1_settings_download_policy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Detail */
        get: operations["health_detail_api_v1_health_detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media-file/{relative_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Media File */
        get: operations["media_file_api_v1_media_file__relative_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArchiveInputSummaryResponse */
        ArchiveInputSummaryResponse: {
            /**
             * Input Record Count
             * @default 0
             */
            input_record_count: number;
            /**
             * Unique Tweet Count
             * @default 0
             */
            unique_tweet_count: number;
            /**
             * Duplicate Input Count
             * @default 0
             */
            duplicate_input_count: number;
        } & {
            [key: string]: unknown;
        };
        /** ArchiveMediaCountsResponse */
        ArchiveMediaCountsResponse: {
            /**
             * Backfilled Media Count
             * @default 0
             */
            backfilled_media_count: number;
            /**
             * Verified Media Count
             * @default 0
             */
            verified_media_count: number;
            /**
             * Missing Media Count
             * @default 0
             */
            missing_media_count: number;
            /**
             * Corrupt Media Count
             * @default 0
             */
            corrupt_media_count: number;
        } & {
            [key: string]: unknown;
        };
        /** ArchiveRecord */
        ArchiveRecord: {
            /** Url */
            url: string;
            /** Author Username */
            author_username?: string | null;
            /** Author Display Name */
            author_display_name?: string | null;
            /** Text */
            text?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Datetime */
            datetime?: string | null;
            /** Collected At */
            collected_at?: string | null;
            /** Source Url */
            source_url?: string | null;
        };
        /** ArchiveRunDetailResponse */
        ArchiveRunDetailResponse: {
            /** Id */
            id: number;
            /** Trigger Type */
            trigger_type: string;
            /** Input Path */
            input_path?: string | null;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Result */
            result?: components["schemas"]["ArchiveRunResultResponse"] | {
                [key: string]: unknown;
            } | null;
            /** Error Message */
            error_message?: string | null;
            /** Items */
            items: components["schemas"]["ArchiveRunItemResponse"][];
        } & {
            [key: string]: unknown;
        };
        /** ArchiveRunItemResponse */
        ArchiveRunItemResponse: {
            /** Id */
            id: number;
            /** Tweet Id */
            tweet_id: string;
            /** Status */
            status: string;
            /** Retry Count */
            retry_count: number;
            /** Error Category */
            error_category?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Linked Item Id */
            linked_item_id?: number | null;
            /** Last Attempt At */
            last_attempt_at?: string | null;
            /** Next Attempt At */
            next_attempt_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Attempts */
            attempts?: components["schemas"]["DownloadAttemptResponse"][];
        } & {
            [key: string]: unknown;
        };
        /** ArchiveRunResultResponse */
        ArchiveRunResultResponse: {
            /** Pipeline Version */
            pipeline_version?: string | null;
            /** Scope */
            scope?: string | null;
            /** Input */
            input?: components["schemas"]["ArchiveInputSummaryResponse"] | {
                [key: string]: unknown;
            };
            /** Tasks */
            tasks?: components["schemas"]["ArchiveTaskCountsResponse"] | {
                [key: string]: unknown;
            };
            /** Media */
            media?: components["schemas"]["ArchiveMediaCountsResponse"] | {
                [key: string]: unknown;
            };
            /** Library Snapshot */
            library_snapshot?: components["schemas"]["LibrarySnapshotResponse"] | {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** ArchiveRunRowResponse */
        ArchiveRunRowResponse: {
            /** Id */
            id: number;
            /** Trigger Type */
            trigger_type: string;
            /** Input Path */
            input_path?: string | null;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Result */
            result?: components["schemas"]["ArchiveRunResultResponse"] | {
                [key: string]: unknown;
            } | null;
            /** Error Message */
            error_message?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ArchiveRunsPageResponse */
        ArchiveRunsPageResponse: {
            /** Count */
            count: number;
            /** Total Count */
            total_count: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: components["schemas"]["ArchiveRunRowResponse"][];
        } & {
            [key: string]: unknown;
        };
        /** ArchiveSourceDetailResponse */
        ArchiveSourceDetailResponse: {
            /** Id */
            id: number;
            /** Source Type */
            source_type: string;
            /** Source Url */
            source_url?: string | null;
            /** Status */
            status: string;
            /** Label */
            label?: string | null;
            /** Author Username */
            author_username?: string | null;
            /** Cursor State */
            cursor_state?: {
                [key: string]: unknown;
            } | null;
            /** Last Seen Tweet Id */
            last_seen_tweet_id?: string | null;
            /** Newest Seen Tweet Id */
            newest_seen_tweet_id?: string | null;
            /** Oldest Seen Tweet Id */
            oldest_seen_tweet_id?: string | null;
            /** Discovered Count */
            discovered_count: number;
            /** Submitted Count */
            submitted_count: number;
            /** Error Category */
            error_category?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Last Scan At */
            last_scan_at?: string | null;
            /** Next Scan At */
            next_scan_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
            /**
             * Discovered Tweet Count
             * @default 0
             */
            discovered_tweet_count: number;
            /**
             * Unsubmitted Tweet Count
             * @default 0
             */
            unsubmitted_tweet_count: number;
            /**
             * Discovered Media Count
             * @default 0
             */
            discovered_media_count: number;
            /** Latest Discovered At */
            latest_discovered_at?: string | null;
            /** Discovered */
            discovered: components["schemas"]["SourceDiscoveryResponse"][];
            scan_summary: components["schemas"]["SourceScanSummaryResponse"];
            /** Scan Runs */
            scan_runs: components["schemas"]["SourceScanRunResponse"][];
        } & {
            [key: string]: unknown;
        };
        /** ArchiveSourceListResponse */
        ArchiveSourceListResponse: {
            /** Id */
            id: number;
            /** Source Type */
            source_type: string;
            /** Source Url */
            source_url?: string | null;
            /** Status */
            status: string;
            /** Label */
            label?: string | null;
            /** Author Username */
            author_username?: string | null;
            /** Cursor State */
            cursor_state?: {
                [key: string]: unknown;
            } | null;
            /** Last Seen Tweet Id */
            last_seen_tweet_id?: string | null;
            /** Newest Seen Tweet Id */
            newest_seen_tweet_id?: string | null;
            /** Oldest Seen Tweet Id */
            oldest_seen_tweet_id?: string | null;
            /** Discovered Count */
            discovered_count: number;
            /** Submitted Count */
            submitted_count: number;
            /** Error Category */
            error_category?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Last Scan At */
            last_scan_at?: string | null;
            /** Next Scan At */
            next_scan_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
            /**
             * Discovered Tweet Count
             * @default 0
             */
            discovered_tweet_count: number;
            /**
             * Unsubmitted Tweet Count
             * @default 0
             */
            unsubmitted_tweet_count: number;
            /**
             * Discovered Media Count
             * @default 0
             */
            discovered_media_count: number;
            /** Latest Discovered At */
            latest_discovered_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ArchiveSourceResponse */
        ArchiveSourceResponse: {
            /** Id */
            id: number;
            /** Source Type */
            source_type: string;
            /** Source Url */
            source_url?: string | null;
            /** Status */
            status: string;
            /** Label */
            label?: string | null;
            /** Author Username */
            author_username?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ArchiveSubmissionResponse */
        ArchiveSubmissionResponse: {
            /** Run Id */
            run_id: number;
            /** Status */
            status: string;
            input: components["schemas"]["ArchiveInputSummaryResponse"];
            tasks: components["schemas"]["ArchiveTaskCountsResponse"];
        } & {
            [key: string]: unknown;
        };
        /** ArchiveSubmitRequest */
        ArchiveSubmitRequest: {
            /**
             * Trigger Type
             * @default webui
             */
            trigger_type: string;
            /** Records */
            records: components["schemas"]["ArchiveRecord"][];
        };
        /** ArchiveTaskCountsResponse */
        ArchiveTaskCountsResponse: {
            /**
             * Queued Count
             * @default 0
             */
            queued_count: number;
            /**
             * Skipped Verified Count
             * @default 0
             */
            skipped_verified_count: number;
            /**
             * Linked Pending Count
             * @default 0
             */
            linked_pending_count: number;
            /**
             * Verified Count
             * @default 0
             */
            verified_count: number;
            /**
             * Failed Count
             * @default 0
             */
            failed_count: number;
            /**
             * Pending Count
             * @default 0
             */
            pending_count: number;
            /**
             * Processing Count
             * @default 0
             */
            processing_count: number;
            /**
             * Failed Retryable Count
             * @default 0
             */
            failed_retryable_count: number;
        } & {
            [key: string]: unknown;
        };
        /** BackfillRequest */
        BackfillRequest: {
            /**
             * Confirm Full Scan
             * @default false
             */
            confirm_full_scan: boolean;
            /**
             * Normalize Files
             * @default true
             */
            normalize_files: boolean;
        };
        /** DownloadAttemptResponse */
        DownloadAttemptResponse: {
            /** Id */
            id: number;
            /** Job Id */
            job_id?: number | null;
            /** Archive Run Item Id */
            archive_run_item_id?: number | null;
            /** Tweet Id */
            tweet_id?: string | null;
            /** Engine */
            engine?: string | null;
            /** Status */
            status: string;
            /** Exit Code */
            exit_code?: number | null;
            /** Error Category */
            error_category?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** DownloadPolicyResponse */
        DownloadPolicyResponse: {
            /** Queue Batch Size */
            queue_batch_size: number;
            /** Downloader Sleep Min Seconds */
            downloader_sleep_min_seconds: number;
            /** Downloader Sleep Max Seconds */
            downloader_sleep_max_seconds: number;
            /** Default Download Engine */
            default_download_engine: string;
            /** Source Scan Batch Size */
            source_scan_batch_size: number;
            /** Source Scan Sleep Min Seconds */
            source_scan_sleep_min_seconds: number;
            /** Source Scan Sleep Max Seconds */
            source_scan_sleep_max_seconds: number;
        } & {
            [key: string]: unknown;
        };
        /** DuplicateRowResponse */
        DuplicateRowResponse: {
            /** Sha256 */
            sha256: string;
            /** Duplicate Count */
            duplicate_count: number;
            /** Total Size */
            total_size: number;
            /** Tweet Id */
            tweet_id: string;
            /** Tweet Url */
            tweet_url: string;
            /** Author Username */
            author_username?: string | null;
            /** Media Type */
            media_type?: string | null;
            /** Media Status */
            media_status: string;
            /** Local Path */
            local_path?: string | null;
            /** File Size */
            file_size?: number | null;
            /** Media Relative Path */
            media_relative_path: string;
            /** Media Url */
            media_url?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** DuplicatesPageResponse */
        DuplicatesPageResponse: {
            /** Count */
            count: number;
            /** Total Count */
            total_count: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: components["schemas"]["DuplicateRowResponse"][];
            /** Duplicate Groups */
            duplicate_groups: number;
        } & {
            [key: string]: unknown;
        };
        /** ExportRequest */
        ExportRequest: {
            /**
             * Kind
             * @default media
             */
            kind: string;
            /**
             * Status
             * @default verified
             */
            status: string | null;
        };
        /** ExportSummaryResponse */
        ExportSummaryResponse: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Size */
            size: number;
            /** Modified At */
            modified_at: number;
        } & {
            [key: string]: unknown;
        };
        /** FailurePageResponse */
        FailurePageResponse: {
            /** Count */
            count: number;
            /** Total Count */
            total_count: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: components["schemas"]["FailureRowResponse"][];
        } & {
            [key: string]: unknown;
        };
        /** FailureRowResponse */
        FailureRowResponse: {
            /** Tweet Id */
            tweet_id: string;
            /** Tweet Url */
            tweet_url: string;
            /** Author Username */
            author_username?: string | null;
            /** Tweet Status */
            tweet_status: string;
            /** Last Error */
            last_error?: string | null;
            /** Retry Count */
            retry_count: number;
            /** Latest Engine */
            latest_engine?: string | null;
            /** Latest Attempt Status */
            latest_attempt_status?: string | null;
            /** Latest Error Category */
            latest_error_category?: string | null;
            /** Latest Error Message */
            latest_error_message?: string | null;
            /** Latest Exit Code */
            latest_exit_code?: number | null;
            /** Latest Finished At */
            latest_finished_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthDetailResponse */
        HealthDetailResponse: {
            /** Status */
            status: string;
            worker: components["schemas"]["WorkerHealthResponse"];
            db_pool: components["schemas"]["DbPoolHealthResponse"];
            queue: components["schemas"]["QueueHealthResponse"];
            sources: components["schemas"]["SourceHealthResponse"];
            /** Recent Errors */
            recent_errors: components["schemas"]["RecentErrorResponse"][];
        } & {
            [key: string]: unknown;
        };
        /** DbPoolHealthResponse */
        DbPoolHealthResponse: {
            /** Active */
            active: number;
            /** Idle */
            idle: number;
            /** Waiting */
            waiting: number;
            /** Min Size */
            min_size: number;
            /** Max Size */
            max_size: number;
        } & {
            [key: string]: unknown;
        };
        /** LatestRunResponse */
        LatestRunResponse: {
            /** Id */
            id: number;
            /** Trigger Type */
            trigger_type: string;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Error Message */
            error_message?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** LatestScanResponse */
        LatestScanResponse: {
            /** Id */
            id: number;
            /** Source Id */
            source_id: number;
            /** Trigger Type */
            trigger_type: string;
            /** Status */
            status: string;
            /** Requested Limit */
            requested_limit?: number | null;
            /** Error Category */
            error_category?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        } & {
            [key: string]: unknown;
        };
        /** LibrarySnapshotResponse */
        LibrarySnapshotResponse: {
            /**
             * Media Total
             * @default 0
             */
            media_total: number;
            /**
             * Verified Total
             * @default 0
             */
            verified_total: number;
        } & {
            [key: string]: unknown;
        };
        /** MediaAssetResponse */
        MediaAssetResponse: {
            /** Id */
            id: number;
            /** Media Index */
            media_index?: number | null;
            /** Media Type */
            media_type?: string | null;
            /** Media Status */
            media_status: string;
            /** Source Engine */
            source_engine?: string | null;
            /** Local Path */
            local_path?: string | null;
            /** Metadata Path */
            metadata_path?: string | null;
            /** Original Filename */
            original_filename?: string | null;
            /** File Ext */
            file_ext?: string | null;
            /** File Size */
            file_size?: number | null;
            /** Sha256 */
            sha256?: string | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Media Relative Path */
            media_relative_path: string;
            /** Media Url */
            media_url?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** MediaPageResponse */
        MediaPageResponse: {
            /** Count */
            count: number;
            /** Total Count */
            total_count: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: components["schemas"]["MediaRowResponse"][];
        } & {
            [key: string]: unknown;
        };
        /** MediaRowResponse */
        MediaRowResponse: {
            /** Tweet Id */
            tweet_id: string;
            /** Tweet Url */
            tweet_url: string;
            /** Author Username */
            author_username?: string | null;
            /** Author Display Name */
            author_display_name?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Tweet Text */
            tweet_text?: string | null;
            /** Tweet Status */
            tweet_status: string;
            /** Media Index */
            media_index?: number | null;
            /** Media Type */
            media_type?: string | null;
            /** Media Status */
            media_status: string;
            /** Source Engine */
            source_engine?: string | null;
            /** Local Path */
            local_path?: string | null;
            /** File Size */
            file_size?: number | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Media Relative Path */
            media_relative_path: string;
            /** Media Url */
            media_url?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** QueueHealthResponse */
        QueueHealthResponse: {
            /** Pending Items */
            pending_items: number;
            /** Processing Items */
            processing_items: number;
            /** Retryable Failed Items */
            retryable_failed_items: number;
            /** Permanent Failed Items */
            permanent_failed_items: number;
            /** Queued Runs */
            queued_runs: number;
            /** Running Runs */
            running_runs: number;
            latest_run?: components["schemas"]["LatestRunResponse"] | null;
        } & {
            [key: string]: unknown;
        };
        /** RecentErrorResponse */
        RecentErrorResponse: {
            /** Kind */
            kind: string;
            /** Id */
            id: string;
            /** Subject */
            subject: string;
            /** Archive Run Id */
            archive_run_id?: number | null;
            /** Archive Run Item Id */
            archive_run_item_id?: number | null;
            /** Tweet Id */
            tweet_id?: string | null;
            /** Source Id */
            source_id?: number | null;
            /** Source Scan Run Id */
            source_scan_run_id?: number | null;
            /** Target Path */
            target_path?: string | null;
            /** Error Category */
            error_category?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Occurred At */
            occurred_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** RecoverInterruptedRequest */
        RecoverInterruptedRequest: {
            /** Timeout Minutes */
            timeout_minutes?: number | null;
        };
        /** RequeueRequest */
        RequeueRequest: {
            /** Statuses */
            statuses?: string[] | null;
            /** Limit */
            limit?: number | null;
        };
        /** SourceCreateRequest */
        SourceCreateRequest: {
            /** Source Type */
            source_type: string;
            /** Source Url */
            source_url: string;
            /** Label */
            label?: string | null;
            /** Author Username */
            author_username?: string | null;
        };
        /** SourceDiscoveryResponse */
        SourceDiscoveryResponse: {
            /** Id */
            id: number;
            /** Tweet Id */
            tweet_id: string;
            /** Archive Run Id */
            archive_run_id?: number | null;
            /**
             * Discovered At
             * Format: date-time
             */
            discovered_at: string;
            /** Download Status */
            download_status: string;
            /** Author Username */
            author_username?: string | null;
            /** Text */
            text?: string | null;
            /** Raw Payload */
            raw_payload?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** SourceHealthResponse */
        SourceHealthResponse: {
            /** Active Sources */
            active_sources: number;
            /** Paused Sources */
            paused_sources: number;
            /** Failed Sources */
            failed_sources: number;
            /** History Enabled Sources */
            history_enabled_sources: number;
            /** Active Scan Runs */
            active_scan_runs: number;
            latest_scan?: components["schemas"]["LatestScanResponse"] | null;
        } & {
            [key: string]: unknown;
        };
        /** SourceHistoryScanRequest */
        SourceHistoryScanRequest: {
            /**
             * Limit
             * @default 20
             */
            limit: number;
            /**
             * Restart
             * @default false
             */
            restart: boolean;
        };
        /** SourceRecordsRequest */
        SourceRecordsRequest: {
            /** Records */
            records: components["schemas"]["ArchiveRecord"][];
        };
        /** SourceScanRequest */
        SourceScanRequest: {
            /**
             * Limit
             * @default 20
             */
            limit: number;
            /**
             * Restart
             * @default false
             */
            restart: boolean;
        };
        /** SourceScanRunResponse */
        SourceScanRunResponse: {
            /** Id */
            id: number;
            /** Trigger Type */
            trigger_type: string;
            /** Status */
            status: string;
            /** Range Start */
            range_start?: number | null;
            /** Range End */
            range_end?: number | null;
            /** Requested Limit */
            requested_limit?: number | null;
            /** Cursor Before */
            cursor_before?: {
                [key: string]: unknown;
            } | null;
            /** Cursor After */
            cursor_after?: {
                [key: string]: unknown;
            } | null;
            /** Discovered Tweet Count */
            discovered_tweet_count: number;
            /** New Tweet Count */
            new_tweet_count: number;
            /** Duplicate Tweet Count */
            duplicate_tweet_count: number;
            /** Discovered Media Count */
            discovered_media_count: number;
            /** Error Category */
            error_category?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        } & {
            [key: string]: unknown;
        };
        /** SourceScanSummaryResponse */
        SourceScanSummaryResponse: {
            /** Batch Count */
            batch_count: number;
            /** Added Tweet Count */
            added_tweet_count: number;
            /** Last Success At */
            last_success_at?: string | null;
            /** Last Error At */
            last_error_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** SourceStatusRequest */
        SourceStatusRequest: {
            /** Status */
            status: string;
        };
        /** SourceSubmitDiscoveredRequest */
        SourceSubmitDiscoveredRequest: {
            /** Limit */
            limit?: number | null;
        };
        /** SourcesPageResponse */
        SourcesPageResponse: {
            /** Count */
            count: number;
            /** Total Count */
            total_count: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: components["schemas"]["ArchiveSourceListResponse"][];
        } & {
            [key: string]: unknown;
        };
        /** SummaryResponse */
        SummaryResponse: {
            /** Tweet Status Counts */
            tweet_status_counts: {
                [key: string]: number;
            };
            /** Media Count */
            media_count: number;
            /** Failure Count */
            failure_count: number;
            /** Archive Dir */
            archive_dir: string;
            /** Exports */
            exports: components["schemas"]["ExportSummaryResponse"][];
        } & {
            [key: string]: unknown;
        };
        /** TweetDetailResponse */
        TweetDetailResponse: {
            tweet: components["schemas"]["TweetResponse"];
            /** Media */
            media: components["schemas"]["MediaAssetResponse"][];
            /** Attempts */
            attempts: components["schemas"]["DownloadAttemptResponse"][];
        } & {
            [key: string]: unknown;
        };
        /** TweetResponse */
        TweetResponse: {
            /** Tweet Id */
            tweet_id: string;
            /** Tweet Url */
            tweet_url: string;
            /** Author Username */
            author_username?: string | null;
            /** Author Display Name */
            author_display_name?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Tweet Text */
            tweet_text?: string | null;
            /** Tweet Status */
            tweet_status: string;
            /** Last Error */
            last_error?: string | null;
            /** Retry Count */
            retry_count: number;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyRequest */
        VerifyRequest: {
            /** Limit */
            limit?: number | null;
            /**
             * Confirm Full Scan
             * @default false
             */
            confirm_full_scan: boolean;
        };
        /** WorkerHealthResponse */
        WorkerHealthResponse: {
            /** Stop Requested */
            stop_requested: boolean;
            /** Write Lock Held */
            write_lock_held: boolean;
        } & {
            [key: string]: unknown;
        };
        /** WriteActionResponse */
        WriteActionResponse: {
            /** Action */
            action: string;
            /** Status */
            status: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    summary_api_v1_library_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
        };
    };
    media_api_v1_library_media_get: {
        parameters: {
            query?: {
                author?: string | null;
                text?: string | null;
                tweet_status?: string | null;
                media_status?: string | null;
                media_type?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tweet_detail_api_v1_library_tweets__tweet_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tweet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TweetDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    failures_api_v1_library_failures_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailurePageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicates_api_v1_library_duplicates_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicatesPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_runs_api_v1_archive_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                run_status?: string | null;
                tweet_id?: string | null;
                failed_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveRunsPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_run_api_v1_archive_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveSubmissionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_run_detail_api_v1_archive_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveRunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_archive_run_api_v1_archive_runs__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveSubmissionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_sources_api_v1_sources_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                source_status?: string | null;
                source_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_archive_source_api_v1_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_source_detail_api_v1_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveSourceDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_archive_source_records_api_v1_sources__source_id__records_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceRecordsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveSubmissionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_archive_source_discovered_api_v1_sources__source_id__submit_discovered_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceSubmitDiscoveredRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveSubmissionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_archive_source_status_api_v1_sources__source_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_archive_source_api_v1_sources__source_id__scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_archive_source_history_scan_api_v1_sources__source_id__history_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceHistoryScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveSourceDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_archive_source_history_scan_api_v1_sources__source_id__history_scan_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveSourceDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_action_api_v1_actions_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    requeue_action_api_v1_actions_requeue_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequeueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recover_interrupted_action_api_v1_actions_recover_interrupted_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoverInterruptedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_action_api_v1_actions_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    maintenance_backfill_api_v1_maintenance_backfill_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackfillRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    maintenance_verify_api_v1_maintenance_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_events_get: {
        parameters: {
            query?: {
                topics?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_policy_api_v1_settings_download_policy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadPolicyResponse"];
                };
            };
        };
    };
    health_detail_api_v1_health_detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDetailResponse"];
                };
            };
        };
    };
    media_file_api_v1_media_file__relative_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relative_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
