[project]
name = "x-media-archiver-cli"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "typer",
  "rich",
  "pydantic",
  "pydantic-settings",
  "alembic",
  "orjson",
  "psycopg[binary]",
  "psycopg_pool",
  "Pillow==12.3.0",
  "python-dotenv",
  "gallery-dl",
  "yt-dlp",
  "imageio-ffmpeg==0.6.0",
  "fastapi",
  "uvicorn[standard]",
  "pwdlib[argon2]",
]

[project.optional-dependencies]
dev = [
  "debugpy",
  "ruff",
]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["xarchiver"]
